Импортируем библиотеки

In [5]:
import pandas as pd
import requests

Загружаем регистрации

In [6]:
df_reg_1 = pd.read_csv('data/regs_1k.csv')
df_reg_1.describe()

            user_id
count  1.000000e+03
mean   4.488623e+06
std    2.620568e+06
min    2.236800e+04
25%    2.235489e+06
50%    4.473044e+06
75%    6.779707e+06
max    8.881772e+06

In [7]:
df_vis_1 = pd.read_csv('data/visits_1k.csv')
df_vis_1.describe()

,uuid,platform,user_agent,date
count,1000,1000,1000,1000
unique,519,3,28,996
top,251a0926-ece3-4d77-aa42-ab569fdf9fe2,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-01T08:01:45
freq,4,954,71,2

Запрашиваем данные о регистрациях по API за период 2023-03-01 -> 2023-09-01

In [10]:
reg_url = 'https://data-charts-api.hexlet.app/registrations?begin=2023-03-01&end=2023-09-01'
df_reg = pd.read_json(reg_url)

Запрашиваем данные о визитах по API за период 2023-03-01 -> 2023-09-01

In [12]:
vis_url = 'https://data-charts-api.hexlet.app/visits?begin=2023-03-01&end=2023-09-01'
df_vis = pd.read_json(vis_url)